import React from 'react';
import {AbsoluteFill,Composition,registerRoot,useCurrentFrame,interpolate,spring} from 'remotion';
import {Product,Brand,Wave} from './ui';
const FPS=60, D=240, TOTAL=2880;
const BLUE='#0071e3',INK='#1d1d1f',GRAY='#727887',AMBER='#ab6811',GREEN='#138564';
const font='-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const ramp=(t,a,b)=>clamp((t-a)/(b-a),0,1);
const lerp=(t,a,b,x,y)=>x+(y-x)*ramp(t,a,b);
const pop=(t,delay=0)=>spring({frame:Math.max(0,t-delay),fps:FPS,config:{damping:19,stiffness:190,mass:.7}});
const rgba=(hex,alpha)=>hex+Math.round(alpha*255).toString(16).padStart(2,'0');
function Kinetic({text,t,delay=0,size=94,color=INK,style={}}){return <div style={{fontSize:size,fontWeight:650,letterSpacing:-size*.045,lineHeight:1.07,...style}}>{text.split(' ').map((word,i)=>{const p=pop(t,delay+i*5);return <span key={i} style={{display:'inline-block',marginRight:'.23em',transform:`translateY(${(1-p)*85}px) rotate(${(1-p)*8}deg)`,opacity:ramp(t,delay+i*5,delay+i*5+10),color}}>{word}</span>})}</div>}
function Tag({children,color=BLUE}){return <span style={{display:'inline-flex',alignItems:'center',padding:'13px 22px',borderRadius:40,color,background:rgba(color,.085),fontSize:22,fontWeight:560}}>{children}</span>}
function Scene({n,children}){const f=useCurrentFrame();const t=f-n*D;if(t<0||t>=D)return null;const enter=1-Math.pow(1-ramp(t,0,18),3);const exit=ramp(t,D-16,D);return <AbsoluteFill style={{transform:`translateX(${(1-enter)*180-exit*250+t*.06}px) scale(${1+(1-enter)*.09+exit*.07+.06*ramp(t,0,D)})`,opacity:Math.min(ramp(t,0,9),1-exit),filter:`blur(${(1-enter)*9+exit*7}px)`}}>{children(t)}</AbsoluteFill>}
function Glass({children,style={}}){return <div style={{background:'#ffffffec',border:'1px solid white',boxShadow:'0 35px 90px #18376714,inset 0 1px 2px #fff',borderRadius:32,...style}}>{children}</div>}
function Waveform({t,width=1200,height=180,color=BLUE}){return <div style={{display:'flex',height,alignItems:'center',justifyContent:'center',gap:9,width}}>{Array.from({length:65},(_,i)=>{const h=15+(height-25)*Math.abs(Math.sin(i*.76+t*.079)*Math.sin(i*.13-t*.034));return <i key={i} style={{height:h,width:8,borderRadius:10,background:color,opacity:.3+.7*(1-Math.abs(i-32)/35)}}/>})}</div>}
function Cursor({t,x=0,y=0,click=0}){return <div style={{position:'absolute',left:x,top:y,transform:`scale(${1-.12*ramp(t,click,click+5)+.12*ramp(t,click+5,click+12)})`,filter:'drop-shadow(0 5px 5px #0002)'}}><svg width='45' height='55' viewBox='0 0 45 55'><path d='M3 2 L3 42 L14 32 L23 51 L32 46 L23 28 L40 28 Z' fill='#1d1d1f' stroke='white' strokeWidth='3'/></svg>{t>click&&t<click+35&&<div style={{position:'absolute',left:-35,top:-35,width:85,height:85,border:`3px solid ${BLUE}`,borderRadius:'50%',opacity:1-ramp(t,click,click+35),transform:`scale(${.2+ramp(t,click,click+35)*1.4})`}}/>}</div>}
function Task({t,state=0,style={}}){const clarify=state>=2;const accepted=state>=3;return <Glass style={{width:760,padding:40,...style}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:20,color:GRAY}}>ACTION 01</span><Tag color={AMBER}>Pending</Tag></div><div style={{fontSize:40,fontWeight:650,letterSpacing:-1.4,margin:'27px 0 22px'}}>Review the scan result</div><div style={{fontSize:26,color:AMBER,borderLeft:'4px solid #e9b86a',paddingLeft:18}}>Scan result is pending.</div><div style={{display:'flex',gap:20,margin:'29px 0'}}>{[['Responsible person',clarify?'Dr. Lee':'Not yet stated'],['Time or trigger',clarify?'By 3 p.m.':'Needs clarification']].map(([k,v],i)=><div key={k} style={{flex:1,borderRadius:18,background:clarify?'#ebf4ff':'#f6f7fa',padding:23,transform:`translateY(${Math.sin(t*.026+i)*3}px)`,border:`1px solid ${clarify?'#cde3ff':'#eef0f5'}`}}><div style={{fontSize:20,color:GRAY}}>{k}</div><div style={{fontSize:29,fontWeight:600,color:clarify?BLUE:AMBER,marginTop:12}}>{v}</div></div>)}</div><div style={{fontSize:19,color:GRAY,marginBottom:10}}>Condition</div><div style={{fontSize:25}}>Discharge is waiting for the review.</div><div style={{borderTop:'1px solid #e6e9ef',marginTop:28,paddingTop:22,fontSize:22,color:BLUE,display:'flex',justifyContent:'space-between'}}><span>↗ View source evidence</span><span style={{color:GRAY}}>Revision {clarify?'2':'1'}</span></div>{accepted&&<div style={{marginTop:28,background:'#e9f7f1',borderRadius:16,padding:20,color:GREEN,fontSize:26,fontWeight:600}}>✓ Accepted by Nurse Morgan<div style={{fontWeight:400,fontSize:19,color:GRAY,marginTop:9}}>Responsibility acknowledged · work still pending</div></div>}</Glass>}
function Head({title,sub,t}){return <div style={{position:'absolute',left:110,top:105,right:100}}><Kinetic text={title} t={t} size={75}/>{sub&&<div style={{fontSize:29,color:GRAY,marginTop:24,opacity:ramp(t,28,43),transform:`translateY(${(1-pop(t,25))*25}px)`}}>{sub}</div>}</div>}
function Thread({f}){return <><div style={{position:'absolute',width:1150,height:1150,borderRadius:'50%',left:1000+Math.sin(f*.004)*180,top:-300+Math.cos(f*.003)*140,background:'radial-gradient(circle,#bcdcff90,transparent 67%)',transform:`scale(${1+.1*Math.sin(f*.006)})`}}/><div style={{position:'absolute',width:1250,height:1250,borderRadius:'50%',left:-540+Math.cos(f*.003)*130,top:130+Math.sin(f*.004)*160,background:'radial-gradient(circle,#d5d2f777,transparent 67%)'}}/><svg style={{position:'absolute',inset:0}} width='1920' height='1080'><path d={`M-100 ${820+Math.sin(f*.008)*50} C 350 ${200+Math.cos(f*.007)*80}, 1130 ${1300+Math.sin(f*.005)*100}, 2020 ${330+Math.cos(f*.006)*130}`} fill='none' stroke='#b8d7fd' strokeWidth='2' strokeDasharray='7 18' strokeDashoffset={-f*1.3}/></svg></>}
function Film(){const f=useCurrentFrame();const n=Math.floor(f/D);return <AbsoluteFill style={{fontFamily:font,color:INK,background:'#f5f7fc',overflow:'hidden'}}><Thread f={f}/>
<Scene n={0}>{t=><><div style={{position:'absolute',left:120,top:140}}><Kinetic text="Your nurse’s shift ends." t={t} size={103}/><Kinetic text="Your scan result hasn’t arrived." t={t} delay={23} size={83} color={BLUE}/></div><Glass style={{position:'absolute',left:145,top:475,width:830,padding:45,transform:`translateY(${Math.sin(t*.023)*12}px) rotate(-2deg) scale(${.9+.1*pop(t,35)})`,opacity:ramp(t,35,48)}}><Tag>Fictional patient · Demo-17</Tag><div style={{fontSize:49,fontWeight:650,marginTop:25}}>Scan result</div><div style={{display:'flex',gap:20,alignItems:'center',marginTop:24,fontSize:37,color:AMBER}}><span style={{display:'inline-block',transform:`rotate(${t*2}deg)`}}>◌</span> Still waiting</div><div style={{fontSize:26,color:GRAY,marginTop:23}}>Someone still needs to review it.</div></Glass><Glass style={{position:'absolute',left:1215,top:500,width:390,padding:45,transform:`translateY(${Math.cos(t*.023)*13}px) rotate(3deg)`,opacity:ramp(t,65,85)}}><div style={{fontSize:25,color:GRAY}}>Shift change</div><div style={{fontSize:97,color:BLUE,fontWeight:650,letterSpacing:-5,marginTop:23}}>{t<90?'13:59':'14:00'}</div><div style={{fontSize:26,marginTop:23}}>A new nurse takes over.</div></Glass></>}</Scene>
<Scene n={1}>{t=><><Head title='Who makes sure it gets checked?' t={t}/><Glass style={{position:'absolute',left:125,top:340,width:760,padding:38,transform:`translateY(${Math.sin(t*.022)*9}px)`}}><div style={{fontSize:22,color:GRAY}}>Why handoffs matter</div><div style={{fontSize:113,fontWeight:650,color:BLUE,letterSpacing:-6,marginTop:8}}>Nearly 1 in 3</div><div style={{fontSize:29,lineHeight:1.4,marginTop:15}}>medical errors and adverse events are linked to communication and coordination gaps during handoffs and care transitions.</div><div style={{fontSize:20,color:GRAY,marginTop:25}}>Source: AHRQ · 2023 research spotlight</div></Glass><div style={{position:'absolute',left:1110,top:365,opacity:ramp(t,28,43),transform:`translateY(${Math.sin(t*.02)*8+(1-pop(t,28))*80}px)`}}><div style={{fontSize:25,color:GRAY}}>Passing the responsibility</div><div style={{fontSize:47,fontWeight:650,marginTop:25}}>Outgoing nurse</div><div style={{fontSize:70,color:BLUE,margin:'20px 0',transform:`translateX(${Math.sin(t*.034)*20}px)`}}>↓</div><div style={{fontSize:47,fontWeight:650}}>Incoming nurse</div><div style={{marginTop:35}}><Tag color={AMBER}>Follow-up still needs an owner</Tag></div></div></>}</Scene>
<Scene n={2}>{t=><><Head title='Speak naturally.' sub='CareThread · Powered by AssemblyAI' t={t}/><div style={{position:'absolute',left:360,top:375,transform:`scale(${1+.025*Math.sin(t*.028)})`}}><Waveform t={t} width={1200} height={230}/></div><Glass style={{position:'absolute',left:365,top:720,width:1120,padding:36,fontSize:36,transform:`translateY(${Math.sin(t*.025)*8}px)`}}><span style={{color:BLUE,fontWeight:650}}>Sender　</span>{'The scan result is pending.'.slice(0,Math.floor(lerp(t,22,110,0,27)))}<span style={{opacity:Math.sin(t*.15)>0?1:0,color:BLUE}}>│</span></Glass></>}</Scene>
<Scene n={3}>{t=><><Head title='What needs doing? Who will do it?' t={t}/><div style={{position:'absolute',left:100,top:375,transform:`translateY(${Math.sin(t*.02)*8}px)`}}>{['Task','Uncertainty','Owner','Timing'].map((s,i)=><div key={s} style={{fontSize:51,fontWeight:600,marginBottom:35,color:i<2?BLUE:GRAY,opacity:ramp(t,22+i*15,34+i*15),transform:`translateX(${(1-pop(t,22+i*15))*-130}px)`}}>{s} <span style={{color:i<2?GREEN:AMBER,fontSize:35,marginLeft:25}}>{i<2?'✓':'?'}</span></div>)}</div><div style={{position:'absolute',left:910,top:280,transformOrigin:'50% 50%',transform:`perspective(1800px) rotateY(${lerp(t,0,240,-7,2)}deg) translateY(${Math.sin(t*.02)*9}px) scale(${.87+.05*ramp(t,0,240)})`}}><Task t={t}/></div></>}</Scene>
<Scene n={4}>{t=><><Head title='Did the next nurse hear it correctly?' t={t}/><Glass style={{position:'absolute',left:130,top:340,width:1600,padding:42,transform:`translateY(${Math.sin(t*.022)*7}px)`}}><div style={{fontSize:27,color:GRAY}}>Receiver readback</div><div style={{fontSize:59,marginTop:26}}>“The scan was <span style={{background:'#ffedcf',color:AMBER,borderRadius:12,padding:'4px 14px'}}>clear</span>.”</div><div style={{height:3,background:'#e0a63f',marginTop:30,width:`${ramp(t,20,65)*95}%`}}/></Glass><div style={{position:'absolute',left:225,top:710,display:'flex',gap:32,alignItems:'center',transform:`translateY(${(1-pop(t,65))*90}px) scale(${1+.014*Math.sin(t*.05)})`,opacity:ramp(t,65,80)}}><div style={{width:85,height:85,borderRadius:'50%',display:'grid',placeItems:'center',fontSize:54,background:'#ffedcf',color:AMBER}}>!</div><Kinetic text='Pause. Clarify. Confirm.' t={t} delay={65} size={70} color={AMBER}/></div></>}</Scene>
<Scene n={5}>{t=><><Head title='Name the person. Set the time.' t={t}/><div style={{position:'absolute',left:110,top:350,transform:`translateY(${Math.sin(t*.025)*8}px)`}}><Task t={t} state={t>65?2:0}/></div><div style={{position:'absolute',left:1110,top:390}}>{[['Dr. Lee','Named owner'],['By 3 p.m.','Stated timing'],['Still pending','Uncertainty retained']].map(([v,l],i)=><div key={v} style={{marginBottom:40,opacity:ramp(t,60+i*25,75+i*25),transform:`translateX(${(1-pop(t,60+i*25))*180}px)`}}><div style={{fontSize:53,color:i===2?AMBER:BLUE,fontWeight:650}}>{v}</div><div style={{fontSize:25,color:GRAY,marginTop:10}}>{l}</div></div>)}</div><Cursor t={t} x={lerp(t,10,62,1770,670)} y={lerp(t,10,62,950,650)} click={65}/></>}</Scene>
<Scene n={6}>{t=><><Head title='Acknowledged. Still pending.' t={t}/><div style={{position:'absolute',left:100,top:300,transformOrigin:'0 0',transform:`scale(.9) translateY(${Math.sin(t*.02)*6}px)`}}><Task t={t} state={t>40?3:2}/></div><div style={{position:'absolute',left:1070,top:365}}><div style={{width:140,height:140,borderRadius:'50%',background:'#e3f5ed',color:GREEN,fontSize:91,display:'grid',placeItems:'center',transform:`scale(${pop(t,40)})`}}>✓</div><div style={{marginTop:40}}><Kinetic text='Accepted' t={t} delay={45} size={83} color={GREEN}/><div style={{fontSize:40,color:GRAY,margin:'15px 0'}}>does not mean</div><Kinetic text='completed.' t={t} delay={90} size={83}/></div></div></>}</Scene>
<Scene n={7}>{t=><><Head title='See exactly what was said.' t={t}/><div style={{position:'absolute',left:125,top:350,transformOrigin:'0 0',transform:`scale(.76) rotateY(${Math.sin(t*.013)*4}deg) translateY(${Math.sin(t*.022)*9}px)`}}><Task t={t} state={2}/></div><svg style={{position:'absolute',left:760,top:570}} width='290' height='160'><path d='M0 105 C120 105 120 40 285 40' stroke={BLUE} strokeWidth='4' strokeDasharray='400' strokeDashoffset={400*(1-ramp(t,30,90))} fill='none'/></svg><Glass style={{position:'absolute',left:1090,top:395,width:590,padding:42,transform:`perspective(1600px) rotateY(${lerp(t,0,240,-8,2)}deg) translateY(${Math.sin(t*.024)*10}px)`,opacity:ramp(t,65,82)}}><Tag>Source statement #03</Tag><div style={{fontSize:38,lineHeight:1.4,marginTop:30}}>“Dr. Lee will review it by three p.m.; discharge is still waiting for that review.”</div><div style={{fontSize:22,color:GRAY,marginTop:30}}>Sender · Revision 2</div></Glass></>}</Scene>
<Scene n={8}>{t=><><Head title='Speech. Planning. Validation.' t={t}/><div style={{position:'absolute',left:125,right:125,top:390,display:'flex',gap:42}}>{[['01','Voice Agent','Speech + replies'],['02','LLM Gateway','Proposed changes'],['03','CareThread','Validated record']].map(([v,a,b],i)=><Glass key={v} style={{flex:1,padding:40,height:330,opacity:ramp(t,15+i*24,28+i*24),transform:`perspective(1200px) rotateY(${Math.sin(t*.014+i)*4}deg) translateY(${Math.sin(t*.025+i)*11+(1-pop(t,15+i*24))*100}px)`}}><div style={{fontSize:63,fontWeight:650,color:BLUE}}>{v}</div><div style={{fontSize:38,fontWeight:650,marginTop:38}}>{a}</div><div style={{fontSize:28,color:GRAY,marginTop:20}}>{b}</div><div style={{height:4,background:'#e4eefc',borderRadius:9,marginTop:38,overflow:'hidden'}}><div style={{width:'30%',height:'100%',background:BLUE,transform:`translateX(${((t*2+i*100)%550)-150}px)`}}/></div></Glass>)}</div><div style={{position:'absolute',left:130,bottom:155,fontSize:31,color:GRAY}}>Powered by AssemblyAI</div></>}</Scene>
<Scene n={9}>{t=><><Head title='Built. Tested. Ready to try.' t={t}/><div style={{position:'absolute',left:130,right:130,top:335,display:'flex',gap:80}}>{[[80,'automated checks passed'],[1,'synthetic spoken fixture passed']].map(([v,s],i)=><div key={s} style={{flex:1,transform:`translateY(${Math.sin(t*.018+i)*10}px)`}}><div style={{fontSize:220,fontWeight:650,letterSpacing:-12,color:BLUE}}>{Math.round(v*Math.min(1,pop(t,25+i*20)))}</div><div style={{fontSize:39,fontWeight:550,maxWidth:600}}>{s}</div></div>)}</div><div style={{position:'absolute',left:130,bottom:155,fontSize:25,color:GRAY}}>Synthetic testing · Clinical efficacy not validated</div></>}</Scene>
<Scene n={10}>{t=><><div style={{position:'absolute',left:125,top:135}}><Kinetic text='Practice clearer shift changes.' t={t} size={92}/><Kinetic text='Keep the next step clear.' t={t} delay={23} size={92} color={BLUE}/></div><div style={{position:'absolute',left:455,top:370,transformOrigin:'0 0',transform:`perspective(2400px) rotateX(${lerp(t,0,240,9,0)}deg) rotateY(${lerp(t,0,240,7,-4)}deg) rotateZ(-2deg) scale(${lerp(t,0,240,.63,.67)}) translateY(${Math.sin(t*.02)*5}px)`}}><Product stage={3}/></div></>}</Scene>
<Scene n={11}>{t=><><div style={{position:'absolute',left:120,top:170,transform:`translateY(${Math.sin(t*.014)*8}px)`}}><Brand size={68}/><div style={{height:60}}/><Kinetic text='Know what’s unfinished.' t={t} delay={17} size={87}/><Kinetic text='Know who follows up.' t={t} delay={31} size={87} color={BLUE}/><div style={{fontSize:39,color:BLUE,marginTop:58,opacity:ramp(t,65,85),transform:`translateX(${(1-pop(t,65))*70}px)`}}>carethread-six.vercel.app　↗</div></div><div style={{position:'absolute',right:165,top:300,transform:`rotate(${t*.07-8}deg) scale(${1+Math.sin(t*.026)*.045})`}}><Wave size={230} animated/></div><div style={{position:'absolute',left:130,bottom:145,fontSize:26,color:GRAY}}>Clinical communication simulation · Synthetic data only</div></>}</Scene>
<div style={{position:'absolute',left:65,top:37,fontSize:17,color:'#7d8798'}}>CareThread · AssemblyAI Hackathon</div><div style={{position:'absolute',right:65,top:37,fontSize:16,color:'#7d8798'}}>Animated synthetic scenario</div><div style={{position:'absolute',left:65,right:65,bottom:35,display:'flex',gap:10}}>{Array.from({length:12},(_,i)=><div key={i} style={{height:3,flex:1,background:'#dbe2ee',overflow:'hidden'}}><div style={{width:`${ramp(f,i*D,(i+1)*D)*100}%`,height:'100%',background:BLUE}}/></div>)}</div>
</AbsoluteFill>}
registerRoot(()=> <Composition id='Dynamic' component={Film} durationInFrames={TOTAL} fps={FPS} width={1920} height={1080}/>);
