import React from 'react';
import {registerRoot, Composition, AbsoluteFill, useCurrentFrame, interpolate, spring} from 'remotion';
const C={ink:'#1d1d1f',gray:'#6e6e73',blue:'#0071e3',line:'#e3e5eb',green:'#16815f',amber:'#a56916'};
const font='-apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif';
const ease=(f,a=0,b=25)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Wave=({size=54,white=false,animated=false})=>{const f=useCurrentFrame();return <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:size/13,width:size,height:size,borderRadius:size*.25,background:white?'#ffffff22':'linear-gradient(145deg,#2598ff,#0062d1)',boxShadow:'inset 0 1px 1px #ffffff88',flexShrink:0}}>{[.25,.52,.77,.42,.62].map((h,i)=><i key={i} style={{width:size*.055,height:size*(animated?h*(.8+.2*Math.sin(f*.18+i)):h),borderRadius:9,background:'white'}}/>)}</div>};
const Brand=({size=42})=><div style={{display:'flex',alignItems:'center',gap:16,fontSize:size,fontWeight:650,letterSpacing:-1.4}}><Wave size={size*1.2}/><span>CareThread</span></div>;
const Label=({children,color=C.gray})=><div style={{fontSize:16,fontWeight:500,color,letterSpacing:.3}}>{children}</div>;
const Pill=({children,color=C.blue,bg='#eaf3ff'})=><span style={{display:'inline-flex',padding:'8px 14px',borderRadius:30,color,background:bg,fontSize:16,fontWeight:550}}>{children}</span>;
function Product({stage=0,compact=false}){const clarified=stage>=2,accepted=stage>=3;return <div style={{width:1400,height:900,background:'#f5f5f7',border:'1px solid #d5d9e3',borderRadius:24,overflow:'hidden',display:'flex',color:C.ink,boxShadow:'0 35px 100px #233c6820, inset 0 1px 0 white'}}>
 <aside style={{width:220,background:'#ededf2',borderRight:'1px solid #d7d7dd',padding:'30px 18px',flexShrink:0}}><Brand size={24}/><div style={{height:44}}/><Label>Workspace</Label>{['Handoff','Conversation','Revision history'].map((v,i)=><div key={v} style={{marginTop:12,padding:14,borderRadius:12,fontSize:17,color:i===0?C.blue:'#565660',background:i===0?'#dceafd':'transparent'}}>{['▤','◌','◷'][i]}　{v}</div>)}<div style={{marginTop:48,padding:14,border:'1px solid #d8dbe3',borderRadius:14,background:'#ffffff88'}}><Label>Current patient</Label><div style={{marginTop:12,fontSize:19,fontWeight:600}}>Patient Demo-17</div><div style={{fontSize:15,color:C.gray,marginTop:6}}>Learning case 01</div></div><div style={{marginTop:320,fontSize:14,color:C.gray}}>Synthetic workspace</div></aside>
 <div style={{flex:1}}><div style={{height:70,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 32px',background:'#ffffffb0',borderBottom:'1px solid #dcdfe5'}}><span style={{fontSize:18,fontWeight:600}}>Nursing handoff　<span style={{fontWeight:400,fontSize:13,color:C.gray}}>SIMULATION</span></span><span style={{fontSize:15,color:C.gray}}>Saved on this device　　<Pill>＋ New handoff</Pill></span></div>
 <div style={{padding:'28px 32px'}}><h2 style={{fontSize:36,letterSpacing:-1,margin:'0 0 8px'}}>Handoff</h2><div style={{color:C.gray,fontSize:17}}>A shared understanding of what happens next.</div>
 <div style={{marginTop:25,background:'white',padding:20,border:'1px solid '+C.line,borderRadius:18,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><b style={{fontSize:21}}>Patient Demo-17</b>　<Pill color={C.gray} bg='#f0f1f5'>Synthetic</Pill><div style={{marginTop:9,color:C.gray,fontSize:15}}>Nursing shift handoff · Learning case 01</div></div><div style={{textAlign:'right'}}><Label>Handoff status</Label><div style={{fontSize:19,fontWeight:600,color:accepted?C.green:C.ink,marginTop:6}}>{accepted?'Acknowledged':'In progress'}</div></div></div>
 <div style={{display:'flex',justifyContent:'space-between',padding:'23px 14px',fontSize:16,color:C.gray}}>{['Capture','Clarify','Read back','Acknowledge'].map((v,i)=><span key={v} style={{color:i<=stage?C.blue:C.gray}}>{i<=stage?'✓':`0${i+1}`}　{v}</span>)}</div>
 <div style={{display:'flex',gap:22}}><div style={{flex:1}}><div style={{fontSize:22,fontWeight:600,marginBottom:14}}>Handoff items　<span style={{color:C.gray,fontSize:16}}>1</span></div>{stage===1&&<div style={{background:'#fff3df',border:'1px solid #efd6a9',borderRadius:13,padding:'14px 18px',marginBottom:12,color:'#885506',fontSize:16}}>Readback needs clarification · 2 differences</div>}
 <div style={{background:'white',border:'1px solid '+C.line,borderRadius:18,padding:24}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Label>ACTION 01</Label><Pill color={C.amber} bg='#fff3df'>Pending</Pill></div><h3 style={{fontSize:27,margin:'15px 0'}}>Review the scan result</h3><div style={{borderLeft:'3px solid #edbe74',padding:'3px 0 3px 14px',fontSize:18,color:'#865820'}}>Scan result is pending.</div><div style={{display:'flex',gap:16,margin:'22px 0'}}>{[['Responsible person',clarified?'Dr. Lee':'Not yet stated'],['Time or trigger',clarified?'By 3 p.m.':'Needs clarification']].map(([k,v])=><div key={k} style={{flex:1,background:'#f5f6f9',borderRadius:12,padding:14}}><Label>{k}</Label><div style={{fontSize:19,fontWeight:600,marginTop:8,color:clarified?C.ink:C.amber}}>{v}</div></div>)}</div><Label>Condition</Label><p style={{fontSize:17,margin:'9px 0 20px'}}>Discharge is waiting for the review.</p><div style={{borderTop:'1px solid '+C.line,paddingTop:16,display:'flex',justifyContent:'space-between',fontSize:15,color:C.blue}}><span>↗ View source evidence</span><span style={{color:C.gray}}>Revision {clarified?'2':'1'}</span></div>{accepted&&<div style={{marginTop:20,color:C.green,fontSize:18,fontWeight:600}}>✓ Accepted by Nurse Morgan<div style={{color:C.gray,fontSize:15,fontWeight:400,marginTop:5}}>Responsibility acknowledged · work still pending</div></div>}</div></div>
 <div style={{width:290,background:'#fff',border:'1px solid '+C.line,borderRadius:18,padding:20,alignSelf:'flex-start'}}><div style={{display:'flex',padding:5,borderRadius:30,background:'#f0f1f5',fontSize:13,gap:8}}><span style={{padding:'8px 10px',background:'white',borderRadius:30,boxShadow:'0 1px 4px #0001'}}>Guided scenario</span><span style={{padding:'8px 5px',color:C.gray}}>Live voice</span></div><div style={{display:'flex',justifyContent:'center',margin:'28px 0 20px'}}><Wave size={68} animated/></div><h3 style={{fontSize:23,textAlign:'center',margin:'15px 0 10px'}}>{accepted?'Handoff acknowledged':'Continue the handoff'}</h3><p style={{fontSize:15,color:C.gray,textAlign:'center',lineHeight:1.5}}>A fictional case,<br/>one step at a time.</p><div style={{background:C.blue,color:'white',borderRadius:30,textAlign:'center',padding:14,fontSize:17,margin:'20px 0 14px'}}>{accepted?'New handoff':'Continue →'}</div><div style={{fontSize:12,textAlign:'center',color:C.gray}}>Scripted replay · no live AI call</div></div></div></div></div></div>}
const Scene=({children,from,to})=>{const f=useCurrentFrame();if(f<from||f>=to)return null;const t=f-from;const alpha=Math.min(ease(t,0,16),interpolate(f,[to-12,to],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}));return <AbsoluteFill style={{opacity:alpha,transform:`translateY(${(1-ease(t))*22}px)`}}>{children}</AbsoluteFill>};
const Header=({title,sub})=><div style={{position:'absolute',top:85,left:115,right:115}}><div style={{fontSize:61,lineHeight:1.12,letterSpacing:-2.3,fontWeight:650}}>{title}</div>{sub&&<div style={{fontSize:27,color:C.gray,marginTop:20}}>{sub}</div>}</div>;
const UIShot=({stage=0,frame,start=0})=><div style={{position:'absolute',left:400,top:250,transformOrigin:'0 0',transform:`perspective(2400px) rotateY(${interpolate(frame,[start,start+250],[-3,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}deg) scale(.8)`}}><Product stage={stage}/></div>;
function Film(){const f=useCurrentFrame();const stages=['The gap','CareThread','Capture','Clarify','Acknowledge','Built with AssemblyAI','Try it'];const current=f<240?0:f<480?1:f<810?2:f<1110?3:f<1440?4:f<1830?5:6;return <AbsoluteFill style={{fontFamily:font,color:C.ink,background:'radial-gradient(ellipse at 80% 75%,#dcecff 0%,transparent 53%), radial-gradient(ellipse at 15% 20%,#e9e8fb 0%,transparent 45%),#f5f6fa'}}>
 <Scene from={0} to={240}><div style={{position:'absolute',left:130,top:170}}><Label>CLINICAL COMMUNICATION</Label><h1 style={{fontSize:94,lineHeight:1.03,letterSpacing:-4,margin:'35px 0'}}>A small change.<br/>A different understanding.</h1></div><div style={{position:'absolute',top:520,left:145,display:'flex',gap:70}}>{[['Sender','“The result is pending.”'],['Receiver','“The scan was clear.”']].map(([who,line],i)=><div key={who} style={{width:745,padding:40,borderRadius:28,background:i?'#fff8ed':'#ffffffc9',border:'1px solid '+(i?'#e9d2ac':'#fff'),opacity:ease(f,25+i*65,55+i*65),transform:`translateY(${(1-ease(f,25+i*65,55+i*65))*30}px)`}}><Label color={i?C.amber:C.blue}>{who}</Label><div style={{fontSize:43,marginTop:25,letterSpacing:-1}}>{line}</div></div>)}</div><div style={{position:'absolute',left:145,bottom:190,fontSize:25,color:C.gray}}>Fictional handoff example</div></Scene>
 <Scene from={240} to={480}><div style={{position:'absolute',left:130,top:125}}><Brand size={56}/><h1 style={{fontSize:79,lineHeight:1.04,letterSpacing:-3,marginTop:45}}>Keep responsibility<br/>in the conversation.</h1><p style={{fontSize:29,color:C.gray,lineHeight:1.6}}>A voice-guided workspace<br/>for clinical handoff practice.</p></div><div style={{position:'absolute',left:845,top:225,transform:`perspective(2400px) rotateY(-12deg) scale(.63)`,transformOrigin:'0 0'}}><Product stage={2}/></div></Scene>
 <Scene from={480} to={810}><Header title='Capture what is still unfinished.' sub='Keep uncertainty. Ask for the missing owner and timing.'/><UIShot stage={0} frame={f} start={480}/></Scene>
 <Scene from={810} to={1110}><Header title={f<960?'When the readback changes, pause.':'Clarify before accepting.'} sub={f<960?'“Pending” must not silently become “clear.”':'Dr. Lee · By 3 p.m. · Result still pending'}/><UIShot stage={f<960?1:2} frame={f} start={810}/></Scene>
 <Scene from={1110} to={1440}><Header title='Acknowledged. Still pending.' sub='The receiver accepts responsibility. Completion stays a separate event.'/><UIShot stage={3} frame={f} start={1110}/></Scene>
 <Scene from={1440} to={1830}><Header title='Speech becomes a reviewable record.' sub='Powered by AssemblyAI. Checked by application rules.'/><div style={{position:'absolute',left:120,right:120,top:340,display:'flex',gap:42}}>{[['01','Conversation','Voice Agent API','Speech input. Spoken replies.'],['02','Proposed changes','LLM Gateway','Structured plans from transcripts.'],['03','Validated record','CareThread rules','Sources. Roles. Revisions.']].map(([n,t,tech,b],i)=><div key={n} style={{flex:1,padding:'44px 36px',background:'#ffffffbb',border:'1px solid white',borderRadius:28,opacity:ease(f,1450+i*30,1480+i*30)}}><div style={{fontSize:60,color:C.blue,fontWeight:600}}>{n}</div><h3 style={{fontSize:34,marginTop:32,letterSpacing:-1}}>{t}</h3><div style={{fontSize:25,color:C.blue}}>{tech}</div><div style={{fontSize:23,color:C.gray,marginTop:25,lineHeight:1.5}}>{b}</div></div>)}</div><div style={{position:'absolute',left:130,top:825,fontSize:28,color:C.gray}}>80 automated checks passed　·　1 synthetic spoken fixture passed</div></Scene>
 <Scene from={1830} to={2160}><div style={{position:'absolute',left:130,top:195}}><Brand size={64}/><h1 style={{fontSize:91,lineHeight:1.06,letterSpacing:-4,margin:'45px 0 28px'}}>The next person knows<br/>what is still unfinished.</h1><p style={{fontSize:30,color:C.gray}}>Start with handoff practice. Learn with clinical educators.</p><div style={{fontSize:32,color:C.blue,marginTop:45}}>carethread-six.vercel.app</div></div><div style={{position:'absolute',left:130,bottom:165,fontSize:21,color:C.gray}}>Synthetic communication simulation · Clinical efficacy not validated</div></Scene>
 <div style={{position:'absolute',left:115,right:115,bottom:50,display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:16,color:'#787f8e'}}><span>CareThread　/　AssemblyAI Voice Agent Hackathon</span><div style={{display:'flex',gap:18}}>{stages.map((s,i)=><span key={s} style={{color:i===current?C.blue:'#9196a0',fontWeight:i===current?650:400}}>{s}</span>)}</div></div><div style={{position:'absolute',bottom:0,left:0,height:5,background:C.blue,width:`${f/2159*100}%`}}/><div style={{position:'absolute',right:45,top:30,fontSize:15,color:'#788193'}}>Animated synthetic scenario</div>
 </AbsoluteFill>}
function Poster(){return <AbsoluteFill style={{fontFamily:font,color:C.ink,background:'radial-gradient(ellipse at 80% 70%,#dceaff,transparent 60%),#f5f6fa'}}><div style={{position:'absolute',left:110,top:90,fontSize:23,color:C.gray}}>AssemblyAI Voice Agent Hackathon</div><div style={{position:'absolute',left:110,top:190}}><Brand size={69}/><h1 style={{fontSize:82,letterSpacing:-3.5,lineHeight:1.02,marginTop:50}}>Clinical handoffs.<br/>Responsibility intact.</h1><p style={{fontSize:29,color:C.gray,lineHeight:1.5}}>Pending work. Clear ownership.<br/>Context preserved.</p><div style={{fontSize:25,color:C.blue,marginTop:55}}>carethread-six.vercel.app</div></div><div style={{position:'absolute',left:875,top:270,transform:'perspective(2400px) rotateY(-10deg) scale(.64)',transformOrigin:'0 0'}}><Product stage={3}/></div><div style={{position:'absolute',left:115,bottom:70,fontSize:19,color:C.gray}}>Synthetic clinical communication simulation</div><div style={{position:'absolute',right:70,bottom:70,fontSize:16,color:C.gray}}>Code-rendered interface illustration</div></AbsoluteFill>}
const Root=()=> <><Composition id='CareThreadFilm' component={Film} durationInFrames={2160} fps={30} width={1920} height={1080}/><Composition id='CareThreadPoster' component={Poster} durationInFrames={1} fps={30} width={1920} height={1080}/><Composition id='Interface' component={()=> <AbsoluteFill style={{fontFamily:font,background:'#f5f5f7',alignItems:'center',justifyContent:'center'}}><Product stage={3}/></AbsoluteFill>} durationInFrames={1} fps={30} width={1400} height={900}/></>;
registerRoot(Root);
