import React from 'react';
import {registerRoot, Composition, AbsoluteFill, useCurrentFrame, interpolate, spring} from 'remotion';
const C={ink:'#1d1d1f',gray:'#6e6e73',blue:'#0071e3',line:'#e3e5eb',green:'#16815f',amber:'#a56916'};
const font='-apple-system, BlinkMacSystemFont, "Helvetica Neue", Arial, sans-serif';
const ease=(f,a=0,b=25)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const Wave=({size=54,white=false,animated=false})=>{const f=useCurrentFrame();return <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:size/13,width:size,height:size,borderRadius:size*.25,background:white?'#ffffff22':'linear-gradient(145deg,#2598ff,#0062d1)',boxShadow:'inset 0 1px 1px #ffffff88',flexShrink:0}}>{[.25,.52,.77,.42,.62].map((h,i)=><i key={i} style={{width:size*.055,height:size*(animated?h*(.8+.2*Math.sin(f*.18+i)):h),borderRadius:9,background:'white'}}/>)}</div>};
const Brand=({size=42})=><div style={{display:'flex',alignItems:'center',gap:16,fontSize:size,fontWeight:650,letterSpacing:-1.4}}><Wave size={size*1.2}/><span>CareThread</span></div>;
const Label=({children,color=C.gray})=><div style={{fontSize:16,fontWeight:500,color,letterSpacing:.3}}>{children}</div>;
const Pill=({children,color=C.blue,bg='#eaf3ff'})=><span style={{display:'inline-flex',padding:'8px 14px',borderRadius:30,color,background:bg,fontSize:16,fontWeight:550}}>{children}</span>;
function Product({stage=0,compact=false}){const clarified=stage>=2,accepted=stage>=3;return <div style={{width:1400,height:900,background:'#f5f5f7',border:'1px solid #d5d9e3',borderRadius:24,overflow:'hidden',display:'flex',color:C.ink,boxShadow:'0 35px 100px #233c6820, inset 0 1px 0 white'}}>
 <aside style={{width:220,background:'#ededf2',borderRight:'1px solid #d7d7dd',padding:'30px 18px',flexShrink:0}}><Brand size={24}/><div style={{height:44}}/><Label>Workspace</Label>{['Handoff','Conversation','Revision history'].map((v,i)=><div key={v} style={{marginTop:12,padding:14,borderRadius:12,fontSize:17,color:i===0?C.blue:'#565660',background:i===0?'#dceafd':'transparent'}}>{['▤','◌','◷'][i]}　{v}</div>)}<div style={{marginTop:48,padding:14,border:'1px solid #d8dbe3',borderRadius:14,background:'#ffffff88'}}><Label>Current patient</Label><div style={{marginTop:12,fontSize:19,fontWeight:600}}>Patient Demo-17</div><div style={{fontSize:15,color:C.gray,marginTop:6}}>Learning case 01</div></div><div style={{marginTop:320,fontSize:14,color:C.gray}}>Synthetic workspace</div></aside>
 <div style={{flex:1}}><div style={{height:70,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 32px',background:'#ffffffb0',borderBottom:'1px solid #dcdfe5'}}><span style={{fontSize:18,fontWeight:600}}>Nursing handoff　<span style={{fontWeight:400,fontSize:13,color:C.gray}}>SIMULATION</span></span><span style={{fontSize:15,color:C.gray}}>Saved on this device　　<Pill>＋ New handoff</Pill></span></div>
 <div style={{padding:'28px 32px'}}><h2 style={{fontSize:36,letterSpacing:-1,margin:'0 0 8px'}}>Handoff</h2><div style={{color:C.gray,fontSize:17}}>A shared understanding of what happens next.</div>
 <div style={{marginTop:25,background:'white',padding:20,border:'1px solid '+C.line,borderRadius:18,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><b style={{fontSize:21}}>Patient Demo-17</b>　<Pill color={C.gray} bg='#f0f1f5'>Synthetic</Pill><div style={{marginTop:9,color:C.gray,fontSize:15}}>Nursing shift handoff · Learning case 01</div></div><div style={{textAlign:'right'}}><Label>Handoff status</Label><div style={{fontSize:19,fontWeight:600,color:accepted?C.green:C.ink,marginTop:6}}>{accepted?'Acknowledged':'In progress'}</div></div></div>
 <div style={{display:'flex',justifyContent:'space-between',padding:'23px 14px',fontSize:16,color:C.gray}}>{['Capture','Clarify','Read back','Acknowledge'].map((v,i)=><span key={v} style={{color:i<=stage?C.blue:C.gray}}>{i<=stage?'✓':`0${i+1}`}　{v}</span>)}</div>
 <div style={{display:'flex',gap:22}}><div style={{flex:1}}><div style={{fontSize:22,fontWeight:600,marginBottom:14}}>Handoff items　<span style={{color:C.gray,fontSize:16}}>1</span></div>{stage===1&&<div style={{background:'#fff3df',border:'1px solid #efd6a9',borderRadius:13,padding:'14px 18px',marginBottom:12,color:'#885506',fontSize:16}}>Readback needs clarification · 2 differences</div>}
 <div style={{background:'white',border:'1px solid '+C.line,borderRadius:18,padding:24}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Label>ACTION 01</Label><Pill color={C.amber} bg='#fff3df'>Pending</Pill></div><h3 style={{fontSize:27,margin:'15px 0'}}>Review the scan result</h3><div style={{borderLeft:'3px solid #edbe74',padding:'3px 0 3px 14px',fontSize:18,color:'#865820'}}>Scan result is pending.</div><div style={{display:'flex',gap:16,margin:'22px 0'}}>{[['Responsible person',clarified?'Dr. Lee':'Not yet stated'],['Time or trigger',clarified?'By 3 p.m.':'Needs clarification']].map(([k,v])=><div key={k} style={{flex:1,background:'#f5f6f9',borderRadius:12,padding:14}}><Label>{k}</Label><div style={{fontSize:19,fontWeight:600,marginTop:8,color:clarified?C.ink:C.amber}}>{v}</div></div>)}</div><Label>Condition</Label><p style={{fontSize:17,margin:'9px 0 20px'}}>Discharge is waiting for the review.</p><div style={{borderTop:'1px solid '+C.line,paddingTop:16,display:'flex',justifyContent:'space-between',fontSize:15,color:C.blue}}><span>↗ View source evidence</span><span style={{color:C.gray}}>Revision {clarified?'2':'1'}</span></div>{accepted&&<div style={{marginTop:20,color:C.green,fontSize:18,fontWeight:600}}>✓ Accepted by Nurse Morgan<div style={{color:C.gray,fontSize:15,fontWeight:400,marginTop:5}}>Responsibility acknowledged · work still pending</div></div>}</div></div>
 <div style={{width:290,background:'#fff',border:'1px solid '+C.line,borderRadius:18,padding:20,alignSelf:'flex-start'}}><div style={{display:'flex',padding:5,borderRadius:30,background:'#f0f1f5',fontSize:13,gap:8}}><span style={{padding:'8px 10px',background:'white',borderRadius:30,boxShadow:'0 1px 4px #0001'}}>Guided scenario</span><span style={{padding:'8px 5px',color:C.gray}}>Live voice</span></div><div style={{display:'flex',justifyContent:'center',margin:'28px 0 20px'}}><Wave size={68} animated/></div><h3 style={{fontSize:23,textAlign:'center',margin:'15px 0 10px'}}>{accepted?'Handoff acknowledged':'Continue the handoff'}</h3><p style={{fontSize:15,color:C.gray,textAlign:'center',lineHeight:1.5}}>A fictional case,<br/>one step at a time.</p><div style={{background:C.blue,color:'white',borderRadius:30,textAlign:'center',padding:14,fontSize:17,margin:'20px 0 14px'}}>{accepted?'New handoff':'Continue →'}</div><div style={{fontSize:12,textAlign:'center',color:C.gray}}>Scripted replay · no live AI call</div></div></div></div></div></div>}

export {Product,Brand,Wave};
